[package]
name = "chunked-map"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.9"
ic-cdk = "0.15.0"
percent-encoding = "2.3.1"
serde = "1.0.203"
serde_bytes = "0.11.15"

